apiVersion: v1
kind: Service
metadata:
  name: proxyweb
  namespace: proxyweb
  labels:
    app: proxyweb
    tier: backend
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: proxyweb
